# Generated by Django 4.1.2 on 2022-10-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightrail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
