# Generated by Django 4.1.2 on 2022-10-13 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lightrail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='wedesday',
            new_name='wednesday',
        ),
    ]
