# Generated by Django 4.1.2 on 2022-10-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightrail', '0002_alter_agency_agency_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_fare_url',
            field=models.URLField(null=True),
        ),
    ]
