# Generated by Django 4.1.2 on 2022-10-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightrail', '0003_alter_agency_agency_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stops',
            name='location_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='parent_station',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='platform_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_lat',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_lon',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_timezone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='wheelchair_boarding',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='zone_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
