# Generated by Django 4.1.2 on 2022-10-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightrail', '0006_alter_stops_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField()),
            ],
        ),
    ]
