# Generated by Django 4.1.2 on 2022-10-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightrail', '0007_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='upload',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
