# Generated by Django 4.1.2 on 2022-10-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightrail', '0008_agency_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(null=True, upload_to='media/')),
            ],
        ),
        migrations.RemoveField(
            model_name='agency',
            name='upload',
        ),
    ]
