# Generated by Django 4.1.2 on 2022-10-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightrail', '0009_csv_remove_agency_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='csv',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
