# Generated by Django 4.1.2 on 2022-10-15 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lightrail', '0010_csv_activated_csv_uploaded'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Csv',
        ),
    ]
