# Generated by Django 4.1.2 on 2022-10-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightrail', '0011_delete_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_lang',
            field=models.CharField(max_length=255),
        ),
    ]
