# Generated by Django 4.1.2 on 2022-10-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightrail', '0013_alter_agency_agency_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stops',
            name='stop_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
